BEGIN;

ALTER TABLE "UserSession" DROP CONSTRAINT IF EXISTS "UserSession_userId_fkey";
ALTER TABLE "ApiUsage" DROP CONSTRAINT IF EXISTS "ApiUsage_apiKeyId_fkey";
ALTER TABLE "ApiKey" DROP CONSTRAINT IF EXISTS "ApiKey_userId_fkey";

DROP TABLE IF EXISTS "AuditLog";
DROP TABLE IF EXISTS "UserSession";
DROP TABLE IF EXISTS "ApiUsage";
DROP TABLE IF EXISTS "ApiKey";

COMMIT;
